<?php
/** Setubridge Technolabs
* http://www.setubridge.com/
* @author SetuBridge
* @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
**/
$templateId = $block->getRequest()->getParam('id');
?>

<script  type="lazy">

    window.generalConfiguration = <?php print_r(json_encode($block->getGeneralConfiguration())); ?>;
    window.getTemplateData = <?php print_r(json_encode($block->getTemplateData($templateId))); ?>;
    window.getMediaCollection = <?php print_r(json_encode($block->getMediaCollection())); ?>;
</script>
<div class="customize-product-content"></div>

<div class="select-design-type" style="display: none">

    <select id="personalization_template_grid_design_type" name="design_type" title="Design Type" class="design_type required-entry _required select admin__control-select" data-ui-id="add-row-form-fieldset-element-select-is-active">
        <option value="0" selected="selected"><?php echo __('Standard') ?></option>
        <option value="2"><?php echo __('Circle') ?></option>
        <option value="1"><?php echo __('Mobile Type') ?></option>
    </select>

</div>


<script  type="lazy">
    var load = true;
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
        ], function ($,modal) {

            setTimeout(function(){ 
                run();
                },
                200
            );

            function run(){

                $(document).on('click',"#personalization_template_grid_customization_template", function() {

                    if(window.getTemplateData != undefined  && window.getTemplateData != null  && window.getTemplateData.template_data && window.getTemplateData.template_data.length){
                        openPopupIframe();
                    }
                    else{

                        var options = {
                            type: 'popup',
                            responsive: true,
                            innerScroll: false,
                            title: 'Your Personalised Template Type',
                            buttons: [
                                {
                                    text: $.mage.__('Confirm'),
                                    class: '',
                                    click: function () {
                                        openPopupIframe();
                                        this.closeModal();
                                    }
                                },
                                {
                                    text: $.mage.__('Cancel'),
                                    class: '',
                                    click: function () {
                                        this.closeModal();
                                    }
                                }
                            ]
                        };

                        var popup = modal(options, $('.select-design-type'));
                        popup.openModal();
                    }
                });

                function openPopupIframe(){

                    var iframeoptions = {
                        type: 'slide',
                        responsive: true,
                        innerScroll: false,
                        title: 'Your Personalised Template',
                        buttons: [{
                            text: $.mage.__('Save changes'),
                            class: 'save-customization',
                            click: function () {

                            }
                        }]
                    };


                    var src = "<?php echo $block->getBaseUrl() ?>personlisation/index.php?templateID=<?php echo $templateId; ?>&display=templatePage";     
                    var wizard_steps_html = '<div class="steps-wizard"><div class="product-designer steps-wizard-navigation"><ul class="product-designer-nav-bar nav-bar"><li class="active add-slide" data-step="add-slide"><a>Slides</a></li><li class="set-configure-area" data-step="set-configure-area"><a>Set Area</a></li><li class="custom-design" data-step="custom-design"><a>Design your own</a></li><li class="save-design" data-step="save-design"><a>Preview</a></li></ul><div class="product-designer-nav-bar-outer-actions nav-bar-outer-actions"><div class="action-wrap"><div class="action-wrap action-wrap-prev"><button type="button" class="action-default action-back-step disabled">Back</button></div><div class="action-wrap action-wrap-next"><button type="button" class="action-default action-primary action-next-step">Next</button><button type="button" class="action-default action-primary action-save-step" style="display: none;">Save</button></div></div></div></div></div>';          

                    var iframe = wizard_steps_html + '<iframe id="customize-product" width="100%" height="900" frameborder="0" src="'+src+'" allowfullscreen></iframe>';

                    $(".customize-product-content").html(iframe);
                    var popup = modal(iframeoptions, $('.customize-product-content'));
                    popup.openModal();

                }
            }
    })
</script>
  