<div class = "cartPopup" id = "cartPopup">
	<div class = "cartPopupInner">
		<h2><span id = "itemName"></span> has been added to cart</h2>
		<a href = "javascript:void(0);" onclick = "cartPopupCont()">Continue Shopping</a>
		<a href = "/checkout/cart">View Cart</a>
		<a href = "/checkout/">Checkout Now</a>
		<a href = "javascript:void(0);" class = "cpClose" onclick = "cartPopupCont()">X</a>
	</div> 
	<div class = "cartPopupClose" onclick = "cartPopupCont()"></div>
</div>