<style>

.loading-mask {
 
    bottom: 0;
    left: 0;
    margin: 0 auto;  
    position: fixed;
    right: 0;
	z-index: 100;
    max-width: 30px;
    background: transparent !important;
    height: 30px;
    border: 4px solid #fff;
    border-top: 4px solid #000;
    border-radius: 50%;
    animation: spin 1s linear infinite;
    top: 50%;
}

@keyframes spin {
    0% { transform: rotate(0deg); }    
    100% { transform: rotate(360deg); }
}
  
</style>  
 
<script>    

/* 	require(['jquery'], function ($) {
			$(document).ready(function () {
				$(document).on('click', '.product-items .product-item-details .swatch-option.color', function (event) {
					event.preventDefault();
					event.stopPropagation();  
					var swatch = $(this);    
					var productLink = swatch.closest('.product-item-info').find('a.product-item-photo').attr('href');         
					if (productLink) {    
						window.location.href = productLink; 
					}     
				});  
				$(document).on('click', '.product-items .product-item-details .swatch-option.image', function (event) {
					event.preventDefault();    
					event.stopPropagation();      
					var swatch = $(this);  
					var productLink = swatch.closest('.product-item-info').find('a.product-item-photo').attr('href');         
					if (productLink) {
						window.location.href = productLink; 
					}     
				});  
		});     
		   
	});  */       


require(['jquery'], function ($) {
    $(document).ready(function () {
       setTimeout(function () {  
        $(document).on('click', '.product-items .product-item-info .swatch-option.color', function (event) {
            event.preventDefault();
            event.stopPropagation();
            var swatch = $(this);
            var productLink = swatch.closest('.product-item-info').find('a.product-item-photo').attr('href');
            if (productLink) {
                window.location.href = productLink;
            }
        });
        $(document).on('click', '.product-items .product-item-info .swatch-option.image', function (event) {
            event.preventDefault();
            event.stopPropagation();
            var swatch = $(this);
            var productLink = swatch.closest('.product-item-info').find('a.product-item-photo').attr('href');
            if (productLink) {
                window.location.href = productLink;
            }
        });
    }, 2000); 
        
    });
});

</script>               