<?php
/** Setubridge Technolabs
* http://www.setubridge.com/
* @author SetuBridge
* @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
**/
?>
<style type="text/css">

#customize-product{
    margin: 5px;
}
#customize-product a.action{
    text-align: center;
}
</style>  
<?php 
$product = $block->getProduct();
$checkedCustomization = $block->checkedCustomization();
$getStatus = $block->getStatus();

if($product->getPersonalization() && $checkedCustomization && $getStatus){
?>
<div id="customize-product">
    <a href="<?php echo $block->getUrl('personalization/index/editor',['product'=>$product->getId(),'itemId'=>$block->getRequest()->getParam('id')]) ?>" data-href="<?php echo $block->getUrl('personalization/index/page',['product'=>$product->getId(),'itemId'=>$block->getRequest()->getParam('id')]) ?>" id="customize-product-button" class="action primary tocart">
    <?= __('Update Customize') ?></a>
</div>
<?php } ?>